[project]
name = "mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jhon Alexander Chaparro Chacon", email = "jhchapar@bancolombia.com.co" }
]
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=4.0.11",
    "httpx>=0.28.1",
    "pydantic-settings>=2.15.0",
    "truststore>=0.10.4",
]

[tool.uv]
package = false
